// ============================================================================
//  lib/site/home-templates-creative.ts — bold, high-variety homepage themes.
//
//  A second wave of homepage layouts (on top of templates.ts + the "extra"
//  set) that push harder on visual identity and section rhythm:
//
//    • Dramatic / cinematic dark layouts (full-bleed academy heroes).
//    • Playful, vibrant kid-and-family designs.
//    • Luxe boutique / couture editorials.
//    • Retro marquee / vintage poster styles.
//    • Motion-forward "reel" layouts using the video block.
//    • Interactive class-tab streams, alternating background rhythm, dividers,
//      and custom heading/copy compositions for more dynamic pages.
//
//  Each is a fully editable block recipe — owners can swap copy, images, colours
//  and typography afterwards. Pure data; safe to import on client + server.
// ============================================================================

import type { PageTemplate } from "./template-types";

export const CREATIVE_HOME_TEMPLATES: PageTemplate[] = [
  // ─── Dramatic / cinematic ────────────────────────────────────────────────
  {
    id: "home-cinematic",
    kind: "home",
    category: "dramatic",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#4338CA",
    suggestedBase: "dark",
    suggestedTypographyId: "cinzel-raleway",
    previewAccent: "#818CF8",
    blocks: [
      {
        type: "hero",
        props: {
          eyebrow: "Now on stage",
          heading: "Lights. Music. You.",
          subheading: "{{tagline}}",
          primaryLabel: "Reserve your place",
          primaryHref: "/enrol",
          secondaryLabel: "Step inside",
          secondaryHref: "/about",
          variant: "academy",
          align: "center",
          primaryButtonStyle: "gradient",
          secondaryButtonStyle: "ghost",
          overlayStrength: "dark",
        },
      },
      { type: "gallery", props: { heading: "Scenes from the studio", _spacing: "spacious" } },
      { type: "statsRow", props: { _bg: "surface" } },
      { type: "testimonials", props: { heading: "Standing ovations", _bg: "tint" } },
      {
        type: "cta",
        props: {
          heading: "The stage is set.",
          subheading: "Step into the spotlight this season.",
          buttonLabel: "Book your trial",
          buttonHref: "/enrol",
        },
      },
    ],
  },
  {
    id: "home-noir",
    kind: "home",
    category: "dramatic",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#C9A227",
    suggestedBase: "dark",
    suggestedTypographyId: "bodoni-work",
    previewAccent: "#E5C76B",
    blocks: [
      {
        type: "hero",
        props: {
          eyebrow: "{{studioName}}",
          heading: "Where discipline meets artistry.",
          subheading: "{{tagline}}",
          primaryLabel: "Discover classes",
          primaryHref: "/classes",
          secondaryLabel: "Meet the faculty",
          secondaryHref: "/people",
          variant: "academy",
          align: "left",
          primaryButtonStyle: "solid",
          secondaryButtonStyle: "outline",
        },
      },
      {
        type: "peopleGrid",
        props: {
          eyebrow: "The company",
          heading: "Artists in residence",
          subheading: "The people behind every performance.",
          source: "staff",
          limit: 6,
          _bg: "surface",
        },
      },
      { type: "gallery", props: { heading: "Backstage", _bg: "base" } },
      { type: "testimonials", props: { _bg: "tint" } },
      { type: "cta" },
    ],
  },
  {
    id: "home-eclipse",
    kind: "home",
    category: "dramatic",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#7C3AED",
    suggestedBase: "dark",
    suggestedTypographyId: "space-inter",
    previewAccent: "#A78BFA",
    blocks: [
      {
        type: "hero",
        props: {
          eyebrow: "A new season begins",
          heading: "Move in a new light.",
          subheading: "{{tagline}}",
          primaryLabel: "Explore programmes",
          primaryHref: "/classes",
          secondaryLabel: "Book a trial",
          secondaryHref: "/enrol",
          variant: "academy",
          align: "center",
          primaryButtonStyle: "gradient",
          secondaryButtonStyle: "ghost",
        },
      },
      {
        type: "statsRow",
        props: {
          items: [
            { label: "Elite", sublabel: "Coaching" },
            { label: "Every level", sublabel: "Welcome" },
            { label: "Studios + theatre", sublabel: "Purpose-built" },
            { label: "A community", sublabel: "That lifts you" },
          ],
          _bg: "tint",
        },
      },
      {
        type: "classTabs",
        props: {
          eyebrow: "Programmes",
          heading: "Find your stream",
          subheading: "Switch between streams to see what fits.",
          _bg: "base",
        },
      },
      { type: "testimonials", props: { _bg: "surface" } },
      { type: "cta" },
    ],
  },

  // ─── Playful / vibrant ───────────────────────────────────────────────────
  {
    id: "home-playful",
    kind: "home",
    category: "playful",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#FF5A5F",
    suggestedBase: "light",
    suggestedTypographyId: "quicksand",
    previewAccent: "#FF5A5F",
    blocks: [
      {
        type: "hero",
        props: {
          eyebrow: "Hello, friend!",
          heading: "Big fun. Real skills.",
          subheading: "{{tagline}}",
          primaryLabel: "Start with a free class",
          primaryHref: "/enrol",
          secondaryLabel: "See all classes",
          secondaryHref: "/classes",
          variant: "default",
          align: "center",
          primaryButtonStyle: "soft",
          secondaryButtonStyle: "ghost",
        },
      },
      {
        type: "features",
        props: {
          heading: "Why kids love it here",
          items: [
            { icon: "🌟", title: "Confidence first", text: "Every child is cheered on, every single class." },
            { icon: "🎉", title: "Seriously fun", text: "Skills sneak in while they're having a blast." },
            { icon: "🤝", title: "Friends for life", text: "A warm, welcoming crew from day one." },
          ],
        },
      },
      { type: "classGrid", props: { heading: "Classes by age", _bg: "surface" } },
      { type: "gallery", props: { heading: "Smiles, all term long", _bg: "tint" } },
      { type: "faq", props: { heading: "Parent questions", _bg: "base" } },
      { type: "contact", props: { _bg: "surface" } },
    ],
  },
  {
    id: "home-carnival",
    kind: "home",
    category: "playful",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#F0408C",
    suggestedBase: "light",
    suggestedTypographyId: "poppins",
    previewAccent: "#F0408C",
    blocks: [
      {
        type: "hero",
        props: {
          eyebrow: "Roll up, roll up",
          heading: "Let's put on a show!",
          subheading: "{{tagline}}",
          primaryLabel: "Join the fun",
          primaryHref: "/enrol",
          secondaryLabel: "What's on",
          secondaryHref: "/news",
          variant: "default",
          align: "center",
          primaryButtonStyle: "gradient",
        },
      },
      { type: "statsRow", props: { _bg: "surface" } },
      {
        type: "classStreams",
        props: {
          eyebrow: "Pick your adventure",
          heading: "So many ways to play",
          viewAllLabel: "See every class",
          viewAllHref: "/classes",
          _bg: "base",
        },
      },
      { type: "testimonials", props: { _bg: "tint" } },
      { type: "gallery", props: { heading: "Showtime moments", _bg: "surface" } },
      {
        type: "cta",
        props: {
          heading: "The fun starts here.",
          subheading: "Grab a free trial and come play.",
          buttonLabel: "Book a trial",
          buttonHref: "/enrol",
        },
      },
    ],
  },
  {
    id: "home-sunny",
    kind: "home",
    category: "playful",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#FB923C",
    suggestedBase: "light",
    suggestedTypographyId: "sora-outfit",
    previewAccent: "#FB923C",
    blocks: [
      {
        type: "hero",
        props: {
          eyebrow: "Rise and move",
          heading: "Every day's a good day to move.",
          subheading: "{{tagline}}",
          primaryLabel: "Find your class",
          primaryHref: "/classes",
          secondaryLabel: "Book a trial",
          secondaryHref: "/enrol",
          variant: "default",
          align: "left",
          primaryButtonStyle: "soft",
        },
      },
      { type: "features", props: { heading: "A brighter way to train", _bg: "surface" } },
      { type: "classGrid", props: { heading: "Sunny-day classes", _bg: "base" } },
      {
        type: "newsFeed",
        props: {
          eyebrow: "On the horizon",
          heading: "What's coming up",
          limit: 3,
          showFilters: false,
          _bg: "tint",
        },
      },
      { type: "cta" },
    ],
  },

  // ─── Luxe / boutique ─────────────────────────────────────────────────────
  {
    id: "home-atelier",
    kind: "home",
    category: "luxe",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#8B7355",
    suggestedBase: "light",
    suggestedTypographyId: "cormorant-inter",
    previewAccent: "#A8896B",
    blocks: [
      {
        type: "hero",
        props: {
          eyebrow: "Maison {{studioName}}",
          heading: "The art of refined movement.",
          subheading: "{{tagline}}",
          primaryLabel: "Make an enquiry",
          primaryHref: "/contact",
          secondaryLabel: "View classes",
          secondaryHref: "/classes",
          variant: "default",
          align: "left",
          primaryButtonStyle: "dark",
          secondaryButtonStyle: "outline",
        },
      },
      {
        type: "richText",
        props: {
          heading: "A considered practice",
          body: "Describe the philosophy behind your studio — the care, the craft, the small details that set the experience apart.\n\nWrite as if welcoming a guest into a space you've thought about deeply.",
          align: "left",
          _spacing: "spacious",
        },
      },
      {
        type: "peopleGrid",
        props: { eyebrow: "The atelier", heading: "Our practitioners", source: "staff", limit: 6, _bg: "surface" },
      },
      { type: "gallery", props: { heading: "The space", _bg: "base" } },
      { type: "testimonials", props: { _bg: "tint" } },
      { type: "cta" },
    ],
  },
  {
    id: "home-couture",
    kind: "home",
    category: "luxe",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#7B2D43",
    suggestedBase: "light",
    suggestedTypographyId: "bodoni-work",
    previewAccent: "#A23B59",
    blocks: [
      {
        type: "pageHeader",
        props: {
          eyebrow: "Season {{studioName}}",
          heading: "Presenting this year's collection.",
          subheading: "{{tagline}}",
          align: "center",
        },
      },
      { type: "gallery", props: { heading: "The collection", _spacing: "spacious", _bg: "base" } },
      {
        type: "richText",
        props: {
          heading: "Behind the curtain",
          body: "Tell the story of your craft — the discipline, the rehearsals, the moments the audience never sees.\n\nThis is where reputation is made.",
          align: "left",
          _bg: "surface",
        },
      },
      { type: "classGrid", props: { heading: "Featured programmes", limit: 6, _bg: "tint" } },
      { type: "cta" },
    ],
  },

  // ─── Retro / vintage ─────────────────────────────────────────────────────
  {
    id: "home-retro",
    kind: "home",
    category: "retro",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#D97706",
    suggestedBase: "light",
    suggestedTypographyId: "bebas-montserrat",
    previewAccent: "#D97706",
    blocks: [
      {
        type: "hero",
        props: {
          eyebrow: "Est. {{studioName}}",
          heading: "Old-school craft. Timeless moves.",
          subheading: "{{tagline}}",
          primaryLabel: "Join the club",
          primaryHref: "/enrol",
          secondaryLabel: "See the timetable",
          secondaryHref: "/schedule",
          variant: "default",
          align: "center",
          primaryButtonStyle: "square",
        },
      },
      { type: "statsRow", props: { _bg: "surface" } },
      { type: "classGrid", props: { heading: "On the bill", _bg: "base" } },
      { type: "testimonials", props: { heading: "Word on the street", _bg: "tint" } },
      { type: "contact", props: { _bg: "surface" } },
    ],
  },
  {
    id: "home-marquee",
    kind: "home",
    category: "retro",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#B91C1C",
    suggestedBase: "dark",
    suggestedTypographyId: "oswald-roboto",
    previewAccent: "#EF4444",
    blocks: [
      {
        type: "hero",
        props: {
          eyebrow: "★ Now showing ★",
          heading: "{{studioName}}",
          subheading: "{{tagline}}",
          primaryLabel: "Get tickets",
          primaryHref: "/enrol",
          secondaryLabel: "Showtimes",
          secondaryHref: "/schedule",
          variant: "academy",
          align: "center",
          primaryButtonStyle: "solid",
          secondaryButtonStyle: "outline",
        },
      },
      {
        type: "newsFeed",
        props: {
          eyebrow: "On the marquee",
          heading: "Headline events",
          limit: 6,
          showFilters: true,
          _bg: "surface",
        },
      },
      {
        type: "schedule",
        props: {
          eyebrow: "This week",
          heading: "Showtimes",
          subheading: "Find your next session.",
          footnote: "",
          _bg: "base",
        },
      },
      { type: "gallery", props: { heading: "From the archives", _bg: "surface" } },
      { type: "cta" },
    ],
  },

  // ─── Editorial (deeper) ──────────────────────────────────────────────────
  {
    id: "home-journal",
    kind: "home",
    category: "editorial",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#334155",
    suggestedBase: "light",
    suggestedTypographyId: "crimson-franklin",
    previewAccent: "#475569",
    blocks: [
      {
        type: "hero",
        props: {
          eyebrow: "The Journal",
          heading: "Notes from the studio.",
          subheading: "{{tagline}}",
          primaryLabel: "Start reading",
          primaryHref: "/news",
          secondaryLabel: "Join us",
          secondaryHref: "/enrol",
          variant: "default",
          align: "left",
        },
      },
      {
        type: "richText",
        props: {
          heading: "Issue one",
          body: "Open with a point of view. What do you believe about movement, teaching, or the people who walk through your doors?\n\nLong-form copy builds trust — give readers something worth their time.",
          align: "left",
          _spacing: "spacious",
        },
      },
      { type: "divider", props: { style: "hair", width: 60, align: "center" } },
      {
        type: "richText",
        props: {
          heading: "Field notes",
          body: "Share a second thread — a recent production, a milestone, a student's journey.\n\nUse **bold** for emphasis and keep the voice unmistakably yours.",
          align: "left",
          _bg: "surface",
        },
      },
      {
        type: "newsFeed",
        props: { eyebrow: "Dispatches", heading: "Latest entries", limit: 4, showFilters: false, _bg: "base" },
      },
      { type: "cta" },
    ],
  },
  {
    id: "home-broadsheet",
    kind: "home",
    category: "editorial",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#1F2937",
    suggestedBase: "light",
    suggestedTypographyId: "eb-karla",
    previewAccent: "#374151",
    blocks: [
      {
        type: "pageHeader",
        props: {
          eyebrow: "Since {{studioName}}",
          heading: "The studio, in print.",
          subheading: "{{tagline}}",
          align: "left",
        },
      },
      {
        type: "newsFeed",
        props: { eyebrow: "Front page", heading: "Headlines", limit: 6, showFilters: true, _bg: "base" },
      },
      { type: "classGrid", props: { heading: "In this edition", limit: 6, _bg: "surface" } },
      { type: "testimonials", props: { heading: "Letters to the editor", _bg: "tint" } },
      { type: "contact", props: { _bg: "base" } },
    ],
  },

  // ─── Visual (deeper) ─────────────────────────────────────────────────────
  {
    id: "home-lookbook",
    kind: "home",
    category: "visual",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#E84A8A",
    suggestedBase: "light",
    suggestedTypographyId: "playfair-source",
    previewAccent: "#E84A8A",
    blocks: [
      {
        type: "hero",
        props: {
          eyebrow: "Lookbook",
          heading: "{{studioName}}",
          subheading: "{{tagline}}",
          primaryLabel: "View classes",
          primaryHref: "/classes",
          secondaryLabel: "",
          secondaryHref: "",
          variant: "default",
          align: "center",
        },
      },
      { type: "gallery", props: { heading: "The lookbook", _spacing: "spacious" } },
      { type: "statsRow", props: { _bg: "surface" } },
      { type: "testimonials", props: { _bg: "tint" } },
      { type: "cta" },
    ],
  },
  {
    id: "home-reel",
    kind: "home",
    category: "visual",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#0EA5A4",
    suggestedBase: "dark",
    suggestedTypographyId: "instrument",
    previewAccent: "#2DD4BF",
    blocks: [
      {
        type: "hero",
        props: {
          eyebrow: "Showreel",
          heading: "Press play on your potential.",
          subheading: "{{tagline}}",
          primaryLabel: "Book a trial",
          primaryHref: "/enrol",
          secondaryLabel: "Browse classes",
          secondaryHref: "/classes",
          variant: "academy",
          align: "left",
          primaryButtonStyle: "gradient",
          secondaryButtonStyle: "ghost",
        },
      },
      { type: "heading", props: { text: "Watch us move", level: "h2", align: "center", _bg: "base", _spacing: "compact" } },
      {
        type: "videoBlock",
        props: { autoplay: false, loop: false, muted: true, controls: true, _bg: "base", _spacing: "compact" },
      },
      { type: "gallery", props: { heading: "More moments", _bg: "surface" } },
      { type: "cta" },
    ],
  },

  // ─── Modern (deeper) ─────────────────────────────────────────────────────
  {
    id: "home-grid",
    kind: "home",
    category: "modern",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#2563EB",
    suggestedBase: "light",
    suggestedTypographyId: "manrope",
    previewAccent: "#2563EB",
    blocks: [
      {
        type: "hero",
        props: {
          eyebrow: "{{studioName}}",
          heading: "A system for serious progress.",
          subheading: "{{tagline}}",
          primaryLabel: "Explore programmes",
          primaryHref: "/classes",
          secondaryLabel: "Book a trial",
          secondaryHref: "/enrol",
          variant: "academy",
          align: "left",
        },
      },
      {
        type: "classTabs",
        props: { eyebrow: "Programmes", heading: "Built level by level", _bg: "surface" },
      },
      { type: "statsRow", props: { _bg: "base" } },
      { type: "features", props: { heading: "How we teach", _bg: "tint" } },
      { type: "cta" },
    ],
  },
  {
    id: "home-pulse",
    kind: "home",
    category: "modern",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#65A30D",
    suggestedBase: "light",
    suggestedTypographyId: "urbanist",
    previewAccent: "#84CC16",
    blocks: [
      {
        type: "hero",
        props: {
          eyebrow: "Find your rhythm",
          heading: "Show up. Level up.",
          subheading: "{{tagline}}",
          primaryLabel: "Start today",
          primaryHref: "/enrol",
          secondaryLabel: "View schedule",
          secondaryHref: "/schedule",
          variant: "academy",
          align: "center",
          primaryButtonStyle: "solid",
        },
      },
      {
        type: "statsRow",
        props: {
          items: [
            { label: "Real", sublabel: "Results" },
            { label: "Every level", sublabel: "Welcome" },
            { label: "Expert", sublabel: "Coaches" },
            { label: "A crew", sublabel: "That pushes you" },
          ],
          _bg: "surface",
        },
      },
      { type: "classGrid", props: { heading: "Train your way", _bg: "base" } },
      { type: "testimonials", props: { _bg: "tint" } },
      { type: "faq", props: { heading: "New here? Start here.", _bg: "surface" } },
      { type: "cta" },
    ],
  },

  // ─── Bold (deeper) ───────────────────────────────────────────────────────
  {
    id: "home-impact",
    kind: "home",
    category: "bold",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#EAB308",
    suggestedBase: "dark",
    suggestedTypographyId: "bebas-montserrat",
    previewAccent: "#FACC15",
    blocks: [
      {
        type: "hero",
        props: {
          eyebrow: "{{studioName}}",
          heading: "Go all in.",
          subheading: "{{tagline}}",
          primaryLabel: "Claim your spot",
          primaryHref: "/enrol",
          secondaryLabel: "See classes",
          secondaryHref: "/classes",
          variant: "academy",
          align: "center",
          primaryButtonStyle: "gradient",
          secondaryButtonStyle: "outline",
        },
      },
      { type: "statsRow", props: { _bg: "tint" } },
      {
        type: "classStreams",
        props: {
          eyebrow: "Choose your lane",
          heading: "Where will you start?",
          viewAllLabel: "All classes",
          viewAllHref: "/classes",
          _bg: "surface",
        },
      },
      { type: "gallery", props: { heading: "In motion", _bg: "base" } },
      {
        type: "cta",
        props: {
          heading: "No more someday.",
          subheading: "Your first class is waiting.",
          buttonLabel: "Enrol now",
          buttonHref: "/enrol",
        },
      },
    ],
  },

  // ─── Minimal (deeper) ────────────────────────────────────────────────────
  {
    id: "home-whitespace",
    kind: "home",
    category: "minimal",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#111111",
    suggestedBase: "light",
    suggestedTypographyId: "archivo",
    previewAccent: "#111111",
    blocks: [
      {
        type: "hero",
        props: {
          eyebrow: "",
          heading: "Less noise. More movement.",
          subheading: "{{tagline}}",
          primaryLabel: "Begin",
          primaryHref: "/enrol",
          secondaryLabel: "",
          secondaryHref: "",
          variant: "default",
          align: "center",
        },
      },
      {
        type: "richText",
        props: {
          heading: "The practice",
          body: "Say one thing, and say it well. What is the single idea at the heart of your studio?\n\nGive it room to breathe.",
          align: "center",
          _spacing: "spacious",
        },
      },
      { type: "divider", props: { style: "hair", width: 40, align: "center" } },
      { type: "classGrid", props: { heading: "Classes", _spacing: "spacious" } },
      { type: "cta" },
    ],
  },
];
