// ============================================================================
//  lib/site/home-templates-extra.ts — additional homepage themes (5–20).
//  Imported by templates.ts; each is a fully editable block recipe.
// ============================================================================

import type { PageTemplate } from "./template-types";

export const EXTRA_HOME_TEMPLATES: PageTemplate[] = [
  {
    id: "home-academy",
    label: "Academy",
    description: "Institution-style layout: bold hero, credentials strip, programmes and faculty.",
    kind: "home",
    category: "professional",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#1B3A6B",
    suggestedBase: "light",
    suggestedTypographyId: "merriweather-opensans",
    previewAccent: "#1B3A6B",
    blocks: [
      {
        type: "hero",
        props: {
          eyebrow: "{{studioName}}",
          heading: "Excellence in every class.",
          subheading: "{{tagline}}",
          primaryLabel: "View programmes",
          primaryHref: "/classes",
          secondaryLabel: "Book a trial",
          secondaryHref: "/enrol",
          variant: "academy",
          align: "center",
        },
      },
      { type: "statsRow", props: { _bg: "tint" } },
      { type: "features", props: { heading: "Why train with us" } },
      {
        type: "classStreams",
        props: {
          eyebrow: "Programmes",
          heading: "Find your stream",
          viewAllLabel: "All classes",
          viewAllHref: "/classes",
        },
      },
      {
        type: "peopleGrid",
        props: {
          eyebrow: "Faculty",
          heading: "Learn from the best",
          subheading: "Experienced instructors dedicated to your progress.",
          source: "staff",
          limit: 6,
        },
      },
      { type: "cta" },
    ],
  },
  {
    id: "home-spotlight",
    label: "Spotlight",
    description: "Performer-first: dramatic hero, instructor spotlight and photo gallery.",
    kind: "home",
    category: "visual",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#C8102E",
    suggestedBase: "dark",
    suggestedTypographyId: "cinzel-raleway",
    previewAccent: "#C8102E",
    blocks: [
      {
        type: "hero",
        props: {
          eyebrow: "Now enrolling",
          heading: "{{studioName}}",
          subheading: "{{tagline}}",
          primaryLabel: "Book a trial",
          primaryHref: "/enrol",
          secondaryLabel: "View schedule",
          secondaryHref: "/schedule",
          variant: "academy",
          align: "left",
        },
      },
      {
        type: "peopleGrid",
        props: {
          eyebrow: "Spotlight",
          heading: "Meet our artists",
          subheading: "The people behind every performance.",
          source: "staff",
          limit: 8,
          _bg: "surface",
        },
      },
      { type: "gallery", props: { heading: "In the studio", _bg: "base" } },
      { type: "testimonials", props: { _bg: "tint" } },
      { type: "cta" },
    ],
  },
  {
    id: "home-magazine",
    label: "Magazine",
    description: "News-first editorial flow — like a studio journal with class highlights.",
    kind: "home",
    category: "editorial",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#0A0A0A",
    suggestedBase: "light",
    suggestedTypographyId: "eb-karla",
    previewAccent: "#0A0A0A",
    blocks: [
      {
        type: "hero",
        props: {
          eyebrow: "Latest",
          heading: "{{studioName}}",
          subheading: "{{tagline}}",
          primaryLabel: "Read news",
          primaryHref: "/news",
          secondaryLabel: "Enrol now",
          secondaryHref: "/enrol",
          variant: "default",
          align: "left",
        },
      },
      {
        type: "newsFeed",
        props: {
          eyebrow: "From the studio",
          heading: "News & events",
          limit: 4,
          showFilters: false,
          viewAllLabel: "All updates",
          viewAllHref: "/news",
          _bg: "surface",
        },
      },
      {
        type: "richText",
        props: {
          heading: "This term at a glance",
          body: "Share highlights, term dates, and what makes your studio special.\n\nFamilies visit your site to stay informed — keep this section fresh.",
          align: "left",
        },
      },
      { type: "classGrid", props: { heading: "Featured classes", limit: 6 } },
      { type: "cta" },
    ],
  },
  {
    id: "home-gallery",
    label: "Gallery",
    description: "Photo portfolio lead — minimal copy, maximum visual impact.",
    kind: "home",
    category: "visual",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#E84A8A",
    suggestedBase: "light",
    suggestedTypographyId: "playfair-source",
    previewAccent: "#E84A8A",
    blocks: [
      {
        type: "hero",
        props: {
          eyebrow: "",
          heading: "{{studioName}}",
          subheading: "{{tagline}}",
          primaryLabel: "View classes",
          primaryHref: "/classes",
          secondaryLabel: "",
          secondaryHref: "",
          variant: "default",
          align: "center",
        },
      },
      { type: "gallery", props: { heading: "Moments from the studio", _spacing: "spacious" } },
      { type: "testimonials", props: { _bg: "tint" } },
      { type: "contact" },
    ],
  },
  {
    id: "home-community",
    label: "Community",
    description: "Social proof heavy — reviews, values and a welcoming class grid.",
    kind: "home",
    category: "community",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#13B6A4",
    suggestedBase: "light",
    suggestedTypographyId: "nunito",
    previewAccent: "#13B6A4",
    blocks: [
      {
        type: "hero",
        props: {
          eyebrow: "Welcome",
          heading: "More than a studio.",
          subheading: "{{tagline}}",
          primaryLabel: "Join us",
          primaryHref: "/enrol",
          secondaryLabel: "Our story",
          secondaryHref: "/about",
          align: "center",
        },
      },
      { type: "testimonials", props: { _bg: "surface" } },
      { type: "features", props: { heading: "What families love about us" } },
      {
        type: "newsFeed",
        props: {
          eyebrow: "Community",
          heading: "What's happening",
          limit: 3,
          showFilters: false,
          _bg: "base",
        },
      },
      { type: "classGrid", props: { _bg: "tint" } },
      { type: "contact" },
    ],
  },
  {
    id: "home-momentum",
    label: "Momentum",
    description: "High-energy fitness vibe — stats, classes and enrol-focused CTA.",
    kind: "home",
    category: "bold",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#5B5BFF",
    suggestedBase: "dark",
    suggestedTypographyId: "oswald-roboto",
    previewAccent: "#5B5BFF",
    blocks: [
      {
        type: "hero",
        props: {
          eyebrow: "{{studioName}}",
          heading: "Train harder. Move smarter.",
          subheading: "{{tagline}}",
          primaryLabel: "Start today",
          primaryHref: "/enrol",
          secondaryLabel: "See schedule",
          secondaryHref: "/schedule",
          variant: "academy",
          align: "center",
        },
      },
      {
        type: "statsRow",
        props: {
          items: [
            { label: "Expert", sublabel: "Coaching" },
            { label: "All levels", sublabel: "Welcome" },
            { label: "Results", sublabel: "You can feel" },
            { label: "Community", sublabel: "That pushes you" },
          ],
        },
      },
      { type: "classGrid", props: { heading: "Pick your class", limit: 8, _bg: "surface" } },
      { type: "faq", props: { heading: "Common questions", _bg: "base" } },
      {
        type: "cta",
        props: {
          heading: "Your first class is waiting.",
          subheading: "Book a trial and feel the difference.",
          buttonLabel: "Enrol now",
          buttonHref: "/enrol",
        },
      },
    ],
  },
  {
    id: "home-elegant",
    label: "Elegant",
    description: "Refined luxury feel — left-aligned hero, story and faculty.",
    kind: "home",
    category: "elegant",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#8B7355",
    suggestedBase: "light",
    suggestedTypographyId: "bodoni-work",
    previewAccent: "#8B7355",
    blocks: [
      {
        type: "hero",
        props: {
          eyebrow: "Est. {{studioName}}",
          heading: "Grace in every movement.",
          subheading: "{{tagline}}",
          primaryLabel: "Discover classes",
          primaryHref: "/classes",
          secondaryLabel: "",
          secondaryHref: "",
          variant: "default",
          align: "left",
        },
      },
      {
        type: "richText",
        props: {
          heading: "A studio of distinction",
          body: "Craft an atmosphere of refinement and care.\n\nDescribe your philosophy, your space, and the experience families can expect.",
          align: "left",
          _spacing: "spacious",
        },
      },
      {
        type: "peopleGrid",
        props: { eyebrow: "Artists", heading: "Our instructors", source: "staff", limit: 6, _bg: "surface" },
      },
      { type: "testimonials", props: { _bg: "tint" } },
      { type: "cta" },
    ],
  },
  {
    id: "home-modern",
    label: "Modern Edge",
    description: "Clean tech-startup aesthetic — streams, stats and sharp CTAs.",
    kind: "home",
    category: "modern",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#0066FF",
    suggestedBase: "light",
    suggestedTypographyId: "space-inter",
    previewAccent: "#0066FF",
    blocks: [
      {
        type: "hero",
        props: {
          eyebrow: "{{studioName}}",
          heading: "The future of training.",
          subheading: "{{tagline}}",
          primaryLabel: "Explore classes",
          primaryHref: "/classes",
          secondaryLabel: "Book a trial",
          secondaryHref: "/enrol",
          variant: "academy",
          align: "left",
        },
      },
      {
        type: "classStreams",
        props: {
          eyebrow: "Programmes",
          heading: "Built for every level",
          viewAllHref: "/classes",
          _bg: "surface",
        },
      },
      { type: "statsRow", props: { _bg: "tint" } },
      { type: "cta" },
    ],
  },
  {
    id: "home-festival",
    label: "Festival",
    description: "Events-driven — news, schedule preview and enrol CTA.",
    kind: "home",
    category: "community",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#C9A227",
    suggestedBase: "dark",
    suggestedTypographyId: "bebas-montserrat",
    previewAccent: "#C9A227",
    blocks: [
      {
        type: "hero",
        props: {
          eyebrow: "What's on",
          heading: "{{studioName}}",
          subheading: "{{tagline}}",
          primaryLabel: "See events",
          primaryHref: "/news",
          secondaryLabel: "View timetable",
          secondaryHref: "/schedule",
          variant: "academy",
          align: "center",
        },
      },
      {
        type: "newsFeed",
        props: {
          heading: "Upcoming events",
          limit: 6,
          showFilters: true,
          _bg: "surface",
        },
      },
      {
        type: "schedule",
        props: {
          eyebrow: "This week",
          heading: "Class timetable",
          subheading: "Find your next session.",
          footnote: "",
          _bg: "base",
        },
      },
      { type: "cta" },
    ],
  },
  {
    id: "home-streams",
    label: "Programmes",
    description: "Class streams explorer with FAQ — ideal for multi-discipline studios.",
    kind: "home",
    category: "professional",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#6B66C9",
    suggestedBase: "light",
    suggestedTypographyId: "dm-serif-dm-sans",
    previewAccent: "#6B66C9",
    blocks: [
      {
        type: "hero",
        props: {
          eyebrow: "Programmes",
          heading: "{{studioName}}",
          subheading: "{{tagline}}",
          primaryLabel: "Browse classes",
          primaryHref: "/classes",
          secondaryLabel: "Enrol",
          secondaryHref: "/enrol",
          align: "center",
        },
      },
      {
        type: "classStreams",
        props: {
          heading: "Choose your path",
          viewAllLabel: "Full class list",
          viewAllHref: "/classes",
          _bg: "surface",
        },
      },
      { type: "classGrid", props: { heading: "All classes", limit: 12, _bg: "base" } },
      { type: "faq", props: { _bg: "tint" } },
      { type: "cta" },
    ],
  },
  {
    id: "home-family",
    label: "Family Welcome",
    description: "Warm and approachable — values, classes and FAQ for new parents.",
    kind: "home",
    category: "community",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#FF6B6B",
    suggestedBase: "light",
    suggestedTypographyId: "quicksand",
    previewAccent: "#FF6B6B",
    blocks: [
      {
        type: "hero",
        props: {
          eyebrow: "All ages welcome",
          heading: "Where every child belongs.",
          subheading: "{{tagline}}",
          primaryLabel: "Book a trial",
          primaryHref: "/enrol",
          secondaryLabel: "View classes",
          secondaryHref: "/classes",
          align: "center",
        },
      },
      { type: "features", props: { heading: "Why families choose us" } },
      { type: "classGrid", props: { heading: "Classes for every age", _bg: "surface" } },
      { type: "faq", props: { heading: "New here? Start here.", _bg: "tint" } },
      { type: "contact" },
    ],
  },
  {
    id: "home-professional",
    label: "Professional",
    description: "Corporate-clean layout — story, values, team and contact.",
    kind: "home",
    category: "professional",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#2D3748",
    suggestedBase: "light",
    suggestedTypographyId: "manrope",
    previewAccent: "#2D3748",
    blocks: [
      {
        type: "pageHeader",
        props: {
          eyebrow: "{{studioName}}",
          heading: "World-class instruction.",
          subheading: "{{tagline}}",
          align: "center",
        },
      },
      {
        type: "richText",
        props: {
          heading: "About our studio",
          body: "Introduce your studio with clarity and confidence.\n\nShare your mission, credentials, and what sets you apart.",
          align: "left",
        },
      },
      { type: "features", props: { _bg: "surface" } },
      {
        type: "peopleGrid",
        props: { heading: "Our team", source: "staff", limit: 8, _bg: "base" },
      },
      { type: "contact", props: { _bg: "tint" } },
    ],
  },
  {
    id: "home-creative",
    label: "Creative Bold",
    description: "Agency-style impact — asymmetric hero, gallery and stats.",
    kind: "home",
    category: "bold",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#FF4081",
    suggestedBase: "dark",
    suggestedTypographyId: "syne-inter",
    previewAccent: "#FF4081",
    blocks: [
      {
        type: "hero",
        props: {
          eyebrow: "Create. Move. Inspire.",
          heading: "{{studioName}}",
          subheading: "{{tagline}}",
          primaryLabel: "Start creating",
          primaryHref: "/enrol",
          secondaryLabel: "Explore",
          secondaryHref: "/classes",
          variant: "academy",
          align: "left",
        },
      },
      { type: "gallery", props: { heading: "Work in progress", _bg: "surface" } },
      { type: "statsRow", props: { _bg: "tint" } },
      { type: "cta" },
    ],
  },
  {
    id: "home-story",
    label: "Storyteller",
    description: "Narrative journey — layered rich text sections building your brand story.",
    kind: "home",
    category: "editorial",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#4A5568",
    suggestedBase: "light",
    suggestedTypographyId: "crimson-franklin",
    previewAccent: "#4A5568",
    blocks: [
      {
        type: "hero",
        props: {
          eyebrow: "Our story",
          heading: "{{studioName}}",
          subheading: "{{tagline}}",
          primaryLabel: "Read more",
          primaryHref: "/about",
          secondaryLabel: "Join us",
          secondaryHref: "/enrol",
          align: "center",
        },
      },
      {
        type: "richText",
        props: {
          heading: "Chapter one",
          body: "Every great studio has an origin story.\n\nTell yours — how it started, what you believe in, and where you're headed.",
          align: "left",
          _spacing: "spacious",
        },
      },
      {
        type: "richText",
        props: {
          heading: "Chapter two",
          body: "Describe the experience — the space, the community, the moments that matter.\n\nFamilies want to feel something before they walk through the door.",
          align: "left",
          _bg: "surface",
        },
      },
      { type: "testimonials", props: { _bg: "tint" } },
      { type: "cta" },
    ],
  },
  {
    id: "home-enrol",
    label: "Enrol Focus",
    description: "Conversion-optimised — classes, social proof and multiple enrol prompts.",
    kind: "home",
    category: "bold",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#22C55E",
    suggestedBase: "light",
    suggestedTypographyId: "jakarta",
    previewAccent: "#22C55E",
    blocks: [
      {
        type: "hero",
        props: {
          eyebrow: "Enrolments open",
          heading: "Start your journey today.",
          subheading: "{{tagline}}",
          primaryLabel: "Book a trial",
          primaryHref: "/enrol",
          secondaryLabel: "View classes",
          secondaryHref: "/classes",
          align: "center",
        },
      },
      { type: "classGrid", props: { heading: "Find your fit", limit: 8 } },
      { type: "testimonials", props: { _bg: "surface" } },
      { type: "faq", props: { _bg: "base" } },
      {
        type: "cta",
        props: {
          heading: "Ready to join {{studioName}}?",
          subheading: "Spaces fill quickly — secure your spot today.",
          buttonLabel: "Enrol now",
          buttonHref: "/enrol",
          _bg: "tint",
        },
      },
    ],
  },
  {
    id: "home-complete",
    label: "Complete",
    description: "Everything on one page — the full studio experience in a single scroll.",
    kind: "home",
    category: "complete",
    title: "Home",
    isHome: true,
    showInNav: false,
    suggestedBrandColor: "#6B66C9",
    suggestedBase: "light",
    suggestedTypographyId: "fraunces-hanken",
    previewAccent: "#6B66C9",
    blocks: [
      {
        type: "hero",
        props: {
          eyebrow: "Welcome to {{studioName}}",
          heading: "Your studio, online.",
          subheading: "{{tagline}}",
          primaryLabel: "Book a trial",
          primaryHref: "/enrol",
          secondaryLabel: "View classes",
          secondaryHref: "/classes",
          variant: "academy",
          align: "center",
        },
      },
      { type: "statsRow" },
      { type: "features", props: { _bg: "surface" } },
      { type: "classStreams", props: { _bg: "base" } },
      { type: "gallery", props: { _bg: "surface" } },
      { type: "testimonials", props: { _bg: "tint" } },
      {
        type: "schedule",
        props: {
          eyebrow: "Timetable",
          heading: "This week's classes",
          subheading: "Browse and plan your week.",
          _bg: "base",
        },
      },
      { type: "cta" },
      { type: "contact", props: { _bg: "surface" } },
    ],
  },
];
